#!/usr/bin/env python3
"""
Measure which P5-22 GUI sensor each shift-register frame slot actually drives.

Why this exists
---------------
The spreadsheet records the *intended* wiring (emulator RTD # = stack*8 +
channel). The physical daisy chain does not necessarily match it, and the
previously observed mapping was measured against a 24-board config on a
44-board chain, so it cannot be trusted. This script measures the real
permutation one slot at a time.

Method
------
Every board is parked at its lowest in-range resistance (highest code, so the
GUI reads cold). One slot at a time is driven to code 0 -- the highest
resistance, so that sensor alone reads hot. You read the P5-22 GUI and type the
name of whichever sensor moved.

Output is `slot,system_sensor` CSV, consumed by build_config_from_excel.py
--slot-map to set each sensor's `position`.

Prerequisites
-------------
- Backend running (no --reload) with the identity-position config generated by
  build_config_from_excel.py with no --slot-map.
- RTD hardware connected; check `hardware_available` in /api/runtime first.

Before doing all 44, try `--slots 1,44`. If slot 1 drives the last sensor and
slot 44 drives the first, the permutation is a plain reversal and you are done.

Dependencies: standard library only.

Exit codes
----------
0 success   2 bad arguments   3 backend unreachable or rejected a request
4 config unusable for calibration   6 CSV write failed
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import sys
import urllib.error
import urllib.request
from pathlib import Path

LOG = logging.getLogger("rtd_slot_calibration")

PARK_HELP = """
Commands at the prompt:
  <name>   the sensor that moved, e.g. T20 or T37C
  ?        unclear / nothing moved -- recorded as unresolved, revisit later
  r        re-drive this slot and ask again
  s        skip without recording
  q        save what has been collected so far and quit
"""


class BackendError(RuntimeError):
    """Backend unreachable, or it refused a request."""


def api_call(base_url: str, path: str, payload: dict | None = None, timeout: float = 5.0) -> dict:
    url = f"{base_url.rstrip('/')}{path}"
    data = None
    headers = {}
    if payload is not None:
        data = json.dumps(payload).encode("utf-8")
        headers["Content-Type"] = "application/json"
    request = urllib.request.Request(url, data=data, headers=headers,
                                     method="POST" if payload is not None else "GET")
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            body = response.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", "replace")[:400]
        raise BackendError(f"{path} returned HTTP {exc.code}: {detail}") from exc
    except urllib.error.URLError as exc:
        raise BackendError(f"cannot reach {url}: {exc.reason}") from exc
    except OSError as exc:
        raise BackendError(f"cannot reach {url}: {exc}") from exc

    if not body:
        return {}
    try:
        return json.loads(body)
    except json.JSONDecodeError as exc:
        raise BackendError(f"{path} returned non-JSON: {body[:200]}") from exc


def park_code(sensor: dict) -> int:
    """Highest code that is still inside the sensor's resistance range.

    code_to_resistance is R = max_res - code * step, so a high code is a low
    resistance, which the GUI shows as a cold reading.
    """
    span = sensor["max_res_ohms"] - sensor["min_res_ohms"]
    step = sensor["res_step_ohms"]
    mask = 0xFF if sensor["bit_width"] == 8 else 0x1F
    if step <= 0:
        return mask
    return max(0, min(mask, int(span / step)))


def code_to_bits(code: int, bit_width: int) -> list[int]:
    """LSB-first, matching ChainDriver._calc_code."""
    return [(code >> index) & 1 for index in range(bit_width)]


def set_board(base_url: str, board_index: int, code: int, bit_width: int) -> None:
    api_call(base_url, f"/api/runtime/rtd/boards/{board_index}",
             {"bits": code_to_bits(code, bit_width)})


def load_sensors(config_path: Path) -> list[dict]:
    try:
        config = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise BackendError(f"cannot read config {config_path}: {exc}") from exc
    sensors = config.get("rtd", {}).get("sensors")
    if not sensors:
        raise BackendError(f"{config_path} has no rtd.sensors")
    return sensors


def read_existing(path: Path) -> dict[int, str]:
    if not path.is_file():
        return {}
    results: dict[int, str] = {}
    try:
        with path.open(newline="", encoding="utf-8") as handle:
            for row in csv.DictReader(handle):
                try:
                    slot = int(float((row.get("slot") or "").strip()))
                except ValueError:
                    continue
                name = (row.get("system_sensor") or "").strip()
                if name:
                    results[slot] = name
    except OSError as exc:
        LOG.warning("cannot read existing %s (%s); starting fresh", path, exc)
        return {}
    LOG.info("resuming: %d slot(s) already recorded in %s", len(results), path)
    return results


def write_results(path: Path, results: dict[int, str]) -> None:
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.writer(handle)
            writer.writerow(["slot", "system_sensor"])
            for slot in sorted(results):
                writer.writerow([slot, results[slot]])
    except OSError as exc:
        raise BackendError(f"cannot write {path}: {exc}") from exc


def main(argv: list[str] | None = None) -> int:
    backend_dir = Path(__file__).resolve().parents[1]

    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--base-url", default="http://127.0.0.1:8000", help="backend base URL")
    parser.add_argument("--config", type=Path, default=backend_dir / "emulator_config.json",
                        help="config the backend is running (read for codes and board indices)")
    parser.add_argument("--out", type=Path, default=Path(__file__).resolve().parent / "rtd_slot_map.csv",
                        help="CSV to write")
    parser.add_argument("--slots", default=None,
                        help="comma-separated slots to probe, e.g. 1,44 (default: all)")
    parser.add_argument("--resume", action="store_true", help="keep slots already present in --out")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO,
                        format="%(levelname)-7s %(message)s")

    if not args.config.is_file():
        LOG.error("config not found: %s", args.config)
        return 2

    # Parse arguments fully before touching the backend, so a typo reports as a
    # bad argument rather than as a connection failure.
    requested_slots: list[int] | None = None
    if args.slots:
        try:
            requested_slots = [int(part) for part in args.slots.split(",") if part.strip()]
        except ValueError:
            LOG.error("--slots must be a comma-separated list of integers, got %r", args.slots)
            return 2
        if not requested_slots:
            LOG.error("--slots was empty")
            return 2

    try:
        sensors = load_sensors(args.config)
        runtime = api_call(args.base_url, "/api/runtime")
    except BackendError as exc:
        LOG.error("%s", exc)
        LOG.error("start the backend first: uvicorn app:app --host 0.0.0.0 --port 8000")
        return 3

    rtd_runtime = runtime.get("rtd", {})
    if not rtd_runtime.get("hardware_available"):
        LOG.warning("backend reports RTD hardware NOT available (%s). Frame bytes will "
                    "change but no board will move.", rtd_runtime.get("hardware_error") or "no error given")

    by_position = {sensor["position"]: sensor for sensor in sensors}
    identity = all(sensor["position"] == sensor["board_index"] + 1 for sensor in sensors)
    if not identity:
        LOG.warning("this config does not use the identity position map. Slot numbers below "
                    "are frame positions, and the recorded map will be relative to THIS "
                    "config, not to the spreadsheet order.")

    if requested_slots is not None:
        unknown = [slot for slot in requested_slots if slot not in by_position]
        if unknown:
            LOG.error("no sensor occupies frame slot(s) %s; this config covers slots %d..%d",
                      unknown, min(by_position), max(by_position))
            return 4
        slots = requested_slots
    else:
        slots = sorted(by_position)

    results = read_existing(args.out) if args.resume else {}
    valid_names = {sensor["sensor_name"] for sensor in sensors}

    LOG.info("parking all %d boards at their cold end", len(sensors))
    try:
        for sensor in sensors:
            set_board(args.base_url, sensor["board_index"], park_code(sensor), sensor["bit_width"])
    except BackendError as exc:
        LOG.error("%s", exc)
        return 3

    print(PARK_HELP)
    print(f"Probing {len(slots)} slot(s). Every board is cold; one at a time goes hot.\n")

    try:
        for slot in slots:
            if args.resume and slot in results:
                LOG.debug("slot %d already recorded as %s, skipping", slot, results[slot])
                continue
            sensor = by_position[slot]
            board_index = sensor["board_index"]

            while True:
                try:
                    set_board(args.base_url, board_index, 0, sensor["bit_width"])
                except BackendError as exc:
                    LOG.error("%s", exc)
                    write_results(args.out, results)
                    LOG.error("partial results saved to %s", args.out)
                    return 3

                answer = input(
                    f"slot {slot:>2} (board_index {board_index:>2}, "
                    f"spreadsheet name {sensor['sensor_name']}) -> which sensor moved? "
                ).strip()

                if answer.lower() == "r":
                    continue
                if answer.lower() == "q":
                    write_results(args.out, results)
                    LOG.info("saved %d result(s) to %s", len(results), args.out)
                    return 0
                if answer.lower() == "s":
                    LOG.info("slot %d skipped", slot)
                    break
                if answer == "?":
                    results[slot] = "UNRESOLVED"
                    LOG.info("slot %d recorded as UNRESOLVED", slot)
                    break
                if answer not in valid_names:
                    print(f"  {answer!r} is not a sensor name in this config. "
                          f"Expected one of T1..T40, T37C..T40C. Try again, or 'r'/'s'/'?'/'q'.")
                    continue
                if answer in results.values():
                    existing = next(s for s, name in results.items() if name == answer)
                    print(f"  {answer} is already recorded for slot {existing}. "
                          f"One sensor cannot occupy two slots -- re-check both.")
                    continue
                results[slot] = answer
                break

            # Return this board to cold before moving on, so only one is ever hot.
            try:
                set_board(args.base_url, board_index, park_code(sensor), sensor["bit_width"])
            except BackendError as exc:
                LOG.error("%s", exc)
                write_results(args.out, results)
                return 3
    except (KeyboardInterrupt, EOFError):
        print()
        LOG.warning("interrupted")
        write_results(args.out, results)
        LOG.info("saved %d result(s) so far to %s", len(results), args.out)
        return 0

    try:
        write_results(args.out, results)
    except BackendError as exc:
        LOG.error("%s", exc)
        return 6

    unresolved = [slot for slot, name in results.items() if name == "UNRESOLVED"]
    LOG.info("wrote %d result(s) to %s", len(results), args.out)
    if unresolved:
        LOG.warning("%d slot(s) unresolved: %s. Re-run with --resume after fixing them; "
                    "build_config_from_excel.py will reject a map containing UNRESOLVED.",
                    len(unresolved), unresolved)
    if len(results) < len(sensors):
        LOG.warning("only %d of %d slots recorded; the map is incomplete and cannot be "
                    "used with --slot-map yet", len(results), len(sensors))
    return 0


if __name__ == "__main__":
    sys.exit(main())
